In [2]:
import numpy as np

In [5]:
lst = [1,2,3,4]
arr = np.array(lst)
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [10]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1.shape

(2, 3)

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [17]:
dict={1: 1, 2:2, 3:3, 4:4, 5:5, 6:6}
np.array(dict.items())

array(dict_items([(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
      dtype=object)

In [22]:
type(arr1)

numpy.ndarray

In [23]:
arr1.dtype

dtype('int32')

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(1, 10, 2).reshape(5, 1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [30]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [31]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
np.arange(50, 1, -2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [35]:
np.arange(10, 1, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [38]:
arr2 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [40]:
arr2.shape

(1, 3, 3)

In [41]:
# between 1 to 20, equally spaced 40 elements
np.linspace(1, 20, 40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [42]:
np.linspace(1,20, 40).shape

(40,)

In [43]:
np.linspace(1,20, 40).reshape(20, 2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.zeros(21).reshape(3,7)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [52]:
np.ones((2, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [54]:
# 2,8 is 2 rows and 8 columns, like that total 5 data will create
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [57]:
# broadcost operation
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [58]:
# identity matrix : all the diogonal elements will be one, remaining will be 0
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [60]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [65]:
# random no generation : uniform distribution
# in uniform distribution values will be between 0 to 1 of 2 rows and 3 columns
print("Random number generation (uniform distribution)")
np.random.rand(2,3)

Random number generation (uniform distribution)


array([[0.03762067, 0.59993032, 0.50319123],
       [0.86017595, 0.52828636, 0.23326853]])

In [66]:
print("Random number following a Normal distribution mean=0 and std=1")
np.random.randn(5,3)

Random number following a Normal distribution mean=0 and std=1


array([[-0.70235227,  1.66230878, -0.50737286],
       [-0.0455891 , -0.28352959, -0.22253184],
       [-0.07843523,  0.3285761 , -0.83975065],
       [-0.15100509,  1.02076727, -1.52847976],
       [ 1.95635462,  0.57995374,  0.89104701]])

In [71]:
print("It will give you one number within min and max value")
np.random.randint(1,100,10)

It will give you one number within min and max value


array([44, 65, 92, 81, 80, 31,  9, 57, 21, 30])

In [72]:
np.random.randint(1,100,(4,4))

array([[53, 60, 35, 14],
       [60,  2,  6, 43],
       [56, 96, 42,  1],
       [71, 27, 47, 94]])

In [75]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
## Slicing
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [80]:
arr[-1:7]

array([], dtype=int32)

In [81]:
arr[-1:7:-1]

array([10,  9,  8])

In [84]:
arr[1:7:-1]

array([], dtype=int32)

In [85]:
arr[-1:3]

array([], dtype=int32)

In [86]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [87]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [90]:
arr1 = np.random.randint(2,100,20).reshape(5,4)
arr1

array([[41, 48, 12, 37],
       [22, 23, 27, 69],
       [28, 83, 87, 83],
       [35, 62, 91, 24],
       [ 9, 77, 75,  2]])

In [92]:
arr1[:3, :]

array([[41, 48, 12, 37],
       [22, 23, 27, 69],
       [28, 83, 87, 83]])

In [93]:
arr1[:3]

array([[41, 48, 12, 37],
       [22, 23, 27, 69],
       [28, 83, 87, 83]])

In [94]:
arr1[:3,:3]

array([[41, 48, 12],
       [22, 23, 27],
       [28, 83, 87]])

In [95]:
arr1

array([[41, 48, 12, 37],
       [22, 23, 27, 69],
       [28, 83, 87, 83],
       [35, 62, 91, 24],
       [ 9, 77, 75,  2]])

In [96]:
arr1[3:, 1:]

array([[62, 91, 24],
       [77, 75,  2]])

In [97]:
arr1[2:4, 1:3]

array([[83, 87],
       [62, 91]])

In [98]:
arr1

array([[41, 48, 12, 37],
       [22, 23, 27, 69],
       [28, 83, 87, 83],
       [35, 62, 91, 24],
       [ 9, 77, 75,  2]])

In [100]:
arr1[2:4, 0:4:3]

array([[28, 83],
       [35, 24]])

In [105]:
# Universal functions
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))
print(arr1)
print("-----------")
print(arr2)

[[79 67 51]
 [47 88 60]
 [87 69 64]]
-----------
[[97 47 23]
 [97 64 59]
 [40 64 61]]


In [106]:
arr1*arr2

array([[7663, 3149, 1173],
       [4559, 5632, 3540],
       [3480, 4416, 3904]])

In [111]:
arr1+arr2

array([[176, 114,  74],
       [144, 152, 119],
       [127, 133, 125]])

In [112]:
arr1 / arr2

array([[0.81443299, 1.42553191, 2.2173913 ],
       [0.48453608, 1.375     , 1.01694915],
       [2.175     , 1.078125  , 1.04918033]])

In [114]:
arr1 - arr2

array([[-18,  20,  28],
       [-50,  24,   1],
       [ 47,   5,   3]])

In [115]:
np.sqrt(36)

6.0

In [116]:
np.sqrt(arr1)

array([[8.88819442, 8.18535277, 7.14142843],
       [6.8556546 , 9.38083152, 7.74596669],
       [9.32737905, 8.30662386, 8.        ]])

In [117]:
np.exp(arr2)

array([[1.33833472e+42, 2.58131289e+20, 9.74480345e+09],
       [1.33833472e+42, 6.23514908e+27, 4.20121040e+25],
       [2.35385267e+17, 6.23514908e+27, 3.10429794e+26]])

In [118]:
np.log10(arr1)

array([[1.89762709, 1.8260748 , 1.70757018],
       [1.67209786, 1.94448267, 1.77815125],
       [1.93951925, 1.83884909, 1.80617997]])

In [122]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
arr1[2:]=1000

In [124]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [126]:
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [127]:
np.dot(arr1, arr2)

array([[ 2683,  3051,  2896],
       [ 5552,  7514,  7434],
       [ 7860,  9986, 10484]])

In [128]:
arr1*arr2

array([[2054,   84,  741],
       [1972, 1624, 3082],
       [ 594, 8342, 3864]])